#!/bin/bash

# Install node components by https://github.com/genxium/Ubuntu14InitScripts/tree/master/backend/node 

sudo su - root -c "npm install -g bower"

# Install MongoDB server, reference https://docs.mongodb.com/manual/tutorial/install-mongodb-on-ubuntu/
mongover=3.2
sudo su - root -c "apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv EA312927"
sudo su - root -c "echo \"deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/$mongover multiverse\" | sudo tee /etc/apt/sources.list.d/mongodb-org-$mongover.list"
sudo su - root -c "apt-get update"
sudo su - root -c "apt-get install -y mongodb-org-server"

bower install 
